#!/bin/bash

##run this script as root or die! don't use sudo!!!
#quick n'dirty....this only works for armv7 (Raspberry Pie 2)


#important: before compiling edit FFDecsa-Section in the Makefiles for SC an DVBAPI:
#from "PARALLEL   ?= ????" to "PARALLEL   ?= PARALLEL_128_4INT"
#and remove all -mmmx -msse -msse2 -msse3 flags ;-) in the same section

echo "deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi" >> /etc/apt/sources.list
apt-get install -y python-software-properties software-properties-common git git-core fontconfig libfontconfig1-dev libjpeg-dev
apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y
basepkg="lirc linux-firmware linux-firmware-nonfree udisks upower xorg alsa-utils mesa-utils librtmp0 libmad0 lm-sensors libmpeg2-4 avahi-daemon libnfs1 consolekit pm-utils samba "
vdrpkg="build-essential libjpeg62-dev libcap-dev libfontconfig1-dev gettext libncursesw5-dev libncurses5-dev pkg-config w-scan"
apt-get build-dep -y vdr kodi
oscampkg="cmake subversion openssl libssl-dev libusb-dev libusb-1.0 libpcsc-perl libpcsclite-dev "
apt-get install -y $basepkg $gfxpkg $kodipkg $mysqlpkg $vdrpkg $oscampkg $pyloadpkg $wifipkg

#vdr
### testing ###
install="/home/pi"
tv_vdr="true"
tv_oscam="true"
### testing end ###

#vdr
if [ "$tv_vdr" = "true" ]
  then
  useradd vdr
  usermod -a -G video vdr
  mkdir -p $install/src /var/vdr /var/vdr/record
  mkdir -p /var/lib/vdr/plugins/vnsiserver /var/lib/vdr/plugins/streamdev-server /var/lib/vdr/plugins/sc /var/lib/vdr/plugins/svdrpservice
  mkdir -p /etc/vdr/plugins/vnsiserver /etc/vdr/plugins/streamdev-server /etc/vdr/plugins/sc /etc/vdr/plugins/svdrpservice
  chown -R :video /var/vdr /var/lib/vdr/
  chmod -R g+w /var/vdr /var/lib/vdr/
  cd /$install/src
  #git clone git://projects.vdr-developer.org/vdr.git

  #use stable release for testing
  wget https://projects.vdr-developer.org/git/vdr.git/snapshot/vdr-vdr-2.2.0.tar.gz
  tar xfvz vdr-vdr-2.2.0.tar.gz
  rm vdr-vdr-2.2.0.tar.gz
  mv vdr-vdr-2.2.0 vdr
  #end code use stable release for testing

cd /$install/src/vdr/PLUGINS/src
  #get plugin sources (streamdev, vnsi, dvbapi, svdrpservice, sc)
  git clone git://projects.vdr-developer.org/vdr-plugin-streamdev.git
  git clone https://github.com/FernetMenta/vdr-plugin-vnsiserver
  git clone https://github.com/manio/vdr-plugin-dvbapi.git
  git clone https://github.com/3PO/vdr-plugin-sc.git
  wget http://vdr.schmirler.de/svdrpservice/vdr-svdrpservice-1.0.0.tgz
  tar -xzf vdr-svdrpservice-1.0.0.tgz
  rm *.tgz
  ln -s vdr-plugin-streamdev streamdev
  ln -s vdr-plugin-vnsiserver vnsiserver
  ln -s vdr-plugin-dvbapi dvbapi
  ln -s vdr-plugin-sc sc
  ln -s svdrpservice-1.0.0 svdrpservice
  nano vdr-plugin-sc/Makefile
  nano vdr-plugin-dvbapi/Makefile
  cd ../../
  make -j4 && make install
fi

#oscam
if [ "$tv_oscam" = "true" ]
        then
                cd $install/src
                rm -R oscam*
                svn co http://streamboard.de.vu/svn/oscam/trunk oscam-svn
                cd oscam-svn*
                mkdir build
                cd build
                cmake .. -DHAVE_LIBUSB=1 -DWEBIF=1 -DHAVE_DVBAPI=1 -DCARDREADER_SMARGO=1 -DUSE_LIBUSB=1 -DWEBIF=1 -DIRDETO_GUESSING=1 -DCS_ANTICASC=1 -DWITH_DEBUG=1 -DCS_WITH_DOUBLECHECK=1 -DCS_LE$
                make -j4 && make install
fi

